site_name: crcf
repo_url: https://github.com/jmbhughes/crcf
site_description: documentation for combination robust cut forests python package
site_author: J. Marcus Hughes

nav:
  - Introduction: 'index.md'
  - Getting Started: 'getting-started.md'
  - Example: 'example.md'
  - Mathematical Background: 'https://github.com/jmbhughes/crcf/blob/master/overview.pdf'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
